services:
  healthcheck-server:
    build: .
    container_name: healthcheck-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - healthcheck-network
    volumes:
      # Volume para logs (opcional)
      - healthcheck-logs:/app/logs
    # Configurações de recursos
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

networks:
  healthcheck-network:
    driver: bridge

volumes:
  healthcheck-logs:
    driver: local 